### PR TITLE
Revert doc snippets not to use backspace characters

### PR DESCRIPTION
**Pull request by ymtszw**
See https://github.com/elixir-lang/language-elixir/issues/68

### CODE REVIEW

**Comment by keathley** [comment]
This looks good to me. Before I merge it I was wondering if it might make more sense to expand the snippet to something like this:

```elixir
@doc """ <- put the cursor right here
"""
```

That way the user simply needs to hit return to start a new line (which will then be indented correctly). Its not something that *has* to be a part of this PR. Just wanted to get some feedback on the idea.

**Comment by ymtszw** [comment]
That looks more than OK, actually. And it's easy to achieve:

```cson
  'doc':
    'prefix': 'doc'
    'body': '@doc """$0\n"""'
```

This will do just the thing.

I'm fine with the change, shall I push this?

**Comment by keathley** [comment]
I think that works great. Lets make sure that it works the same way for `doc` and `moduledoc` and it should be good :+1:

**Comment by ymtszw** [comment]
2d842fc Change applied

**Comment by keathley** [comment]
Sorry about the delay. This looks good to me. Thanks for taking care of this :tada:

**Pull request merged**
